repos:
- repo: local
  hooks:
    - id: isort
      name: Run isort
      entry: isort
      # From the docs it is not clear the difference between `language: python` VS `language: system`
      language: system
      args: ["--profile", "black", --line-length=88]
      exclude: |
        (?x)^(
            models/.*|
            data/.*|
            notebooks/.*|
            __pycache__|
            logs/.*
        )$
    - id: black
      name: Run black
      entry: black
      language: python
      types: [python]
      args: [--line-length=120]
      exclude: |
        (?x)^(
            models/.*|
            data/.*|
            notebooks/.*|
            __pycache__|
            logs/.*
        )$
    - id: flake8
      name: Run flake8
      entry: flake8
      language: system
      exclude: |
        (?x)^(
            models/.*|
            data/.*|
            assets/.*|
            notebooks/.*|
            __pycache__|
            .env|
            logs/.*|
            src/genai_cdd/tests/.*|
            .*.json|
            \S*.toml
        )$
      args: 
          - --max-line-length=120
          - --ignore=D100,D104,D107,E203,W503,W605,E712,E731,E999
          # - --exclude=src/config/retrieval_config.yaml
  # D100 requires all Python files (modules) to have a "public" docstring even if all functions within have a docstring.
  # D104 requires __init__ files to have a docstring
  # D107 requires __init__ files to have a docstring
  # E203 requires no whitespace before ':', does not work with list slicig at the moment
  # W503 requires no binary operators just after a line feed, but that is how black auto-formats our long Spark commands
  # W605 doesn't allow `\d` escape sequences but they are useful in regex (where they are not actually escape sequences)
  # E712 requires alternative syntax for conditionals that isn't Spark compatible
  # E731 does not allow for lambda expressions
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: \.ipynb$
      stages: [commit]
      language: system
      entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
# let's keep this down here for future reference
# - repo: https://github.com/astral-sh/ruff-pre-commit
#   rev: v0.3.4
#   hooks:
#     # Run the linter.
#     - id: ruff
#       args: [ --fix ]
#     # Run the formatter.
#     - id: ruff-format
  
- repo: https://github.com/fpgmaas/deptry.git
  rev: 0.13.0
  hooks:
    - id: deptry
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
  -   id: poetry-check
  -   id: poetry-export
      args: ["--without-hashes", "--format=requirements.txt", "--output=requirements.txt", "--only=main"]
  -   id: poetry-export
      args: ["--without-hashes", "--format=requirements.txt", "--output=requirements-dev.txt", "--only=dev"]